# Generated by Django 6.0.3 on 2026-04-15 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rent_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('purpose', models.TextField()),
                ('age', models.IntegerField(validators=[django.core.validators.MinLengthValidator(18), django.core.validators.MaxLengthValidator(65)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
