# Generated by Django 6.0.3 on 2026-04-17 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_people',
            name='hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
