# Generated by Django 6.0.3 on 2026-04-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField()),
                ('year', models.IntegerField()),
                ('admission_year', models.IntegerField()),
            ],
        ),
    ]
