# Generated by Django 6.0.3 on 2026-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField()),
                ('owner_name', models.CharField()),
                ('contact_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('open_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
